{
    "name": "My First Module",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "My first custom Odoo module",
    "description": "A beginner Odoo module for learning custom models and views.",
    "author": "Afnan",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/customer_sequence.xml",
        "data/invoice_sequence.xml",
        "data/dashboard_data.xml",
        "views/customer_views.xml",
        "views/company_views.xml",
        "views/tag_views.xml",
        "views/customer_note_views.xml",
        "views/customer_activity_views.xml",
        "views/customer_invoice_views.xml",
        "views/document_views.xml",
        "views/dashboard_views.xml",
        "views/report_views.xml",
    ],
    "demo": [
        "demo/demo.xml",
    ],
    "installable": True,
    "application": True,
}
